// Copyright 2020 Goldman Sachs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package org.finos.legend.pure.runtime.java.compiled.compiler;

import org.eclipse.collections.api.RichIterable;
import org.eclipse.collections.api.factory.Lists;
import org.eclipse.collections.api.factory.Maps;
import org.eclipse.collections.api.factory.Sets;
import org.eclipse.collections.api.list.ImmutableList;
import org.eclipse.collections.api.list.MutableList;
import org.eclipse.collections.api.map.MutableMap;
import org.eclipse.collections.impl.block.factory.Functions;
import org.eclipse.collections.impl.utility.ArrayIterate;
import org.eclipse.collections.impl.utility.Iterate;
import org.eclipse.collections.impl.utility.LazyIterate;

import javax.tools.Diagnostic;
import javax.tools.DiagnosticCollector;
import javax.tools.JavaFileObject;
import java.util.EnumMap;
import java.util.Map;
import java.util.regex.Pattern;

/**
 * Error that occurs during compilation of Java files generated by Pure.
 */
public class PureJavaCompileException extends Exception
{
    private static final int MAX_SOURCES_FOR_MESSAGE = 5;
    private static final int MAX_LINES_FOR_MESSAGE = 250;
    private static final long SOURCE_CONTEXT_LINES = 20;

    private final ImmutableList<Diagnostic<? extends JavaFileObject>> diagnostics;

    public PureJavaCompileException(Iterable<Diagnostic<? extends JavaFileObject>> diagnostics)
    {
        super(createMessage(diagnostics));
        this.diagnostics = Lists.immutable.withAll(diagnostics);
    }

    public PureJavaCompileException(DiagnosticCollector<JavaFileObject> diagnosticCollector)
    {
        this(diagnosticCollector.getDiagnostics());
    }

    public RichIterable<Diagnostic<? extends JavaFileObject>> getDiagnostics()
    {
        return this.diagnostics;
    }

    public RichIterable<Diagnostic<? extends JavaFileObject>> getErrorDiagnostics()
    {
        return LazyIterate.select(this.diagnostics, PureJavaCompileException::isErrorDiagnostic);
    }

    private static String createMessage(Iterable<Diagnostic<? extends JavaFileObject>> diagnostics)
    {
        Map<Diagnostic.Kind, MutableList<Diagnostic<? extends JavaFileObject>>> byKind = new EnumMap<>(Diagnostic.Kind.class);
        diagnostics.forEach(d -> byKind.computeIfAbsent(d.getKind(), k -> Lists.mutable.empty()).add(d));
        return byKind.isEmpty() ? "Unknown error compiling generated Java code" : new MessageBuilder(byKind).getMessage();
    }

    private static boolean isErrorDiagnostic(Diagnostic<?> diagnostic)
    {
        return (diagnostic != null) && (Diagnostic.Kind.ERROR == diagnostic.getKind());
    }

    private static String getSourceName(Diagnostic<? extends JavaFileObject> diagnostic)
    {
        JavaFileObject source = diagnostic.getSource();
        return (source == null) ? null : source.getName();
    }

    private static class MessageBuilder
    {
        private final Map<Diagnostic.Kind, MutableList<Diagnostic<? extends JavaFileObject>>> diagnosticsByKind;
        private final Pattern lineSplitter = Pattern.compile("\\R");
        private final MutableList<String> lines = Lists.mutable.empty();

        private MessageBuilder(Map<Diagnostic.Kind, MutableList<Diagnostic<? extends JavaFileObject>>> diagnosticsByKind)
        {
            this.diagnosticsByKind = diagnosticsByKind;
        }

        String getMessage()
        {
            MutableList<Diagnostic<? extends JavaFileObject>> diagnostics;
            String description;
            if (this.diagnosticsByKind.containsKey(Diagnostic.Kind.ERROR))
            {
                diagnostics = this.diagnosticsByKind.get(Diagnostic.Kind.ERROR);
                description = "error";
            }
            else
            {
                diagnostics = Iterate.flatCollect(this.diagnosticsByKind.values(), Functions.identity(), Lists.mutable.empty());
                description = "issue";
            }
            addLine(createSummaryMessage(diagnostics, description));
            MutableMap<String, MutableList<Diagnostic<? extends JavaFileObject>>> bySource = Maps.mutable.empty();
            diagnostics.forEach(diagnostic ->
            {
                printLines(diagnostic.toString());
                bySource.getIfAbsentPut(PureJavaCompileException.getSourceName(diagnostic), Lists.mutable::empty).add(diagnostic);
            });
            bySource.forEachKeyValue(this::printDiagnosticSources);
            return this.lines.makeString("\n");
        }

        private void addLine(String line)
        {
            if (this.lines.size() < MAX_LINES_FOR_MESSAGE)
            {
                this.lines.add(line);
            }
            else if (this.lines.size() == MAX_LINES_FOR_MESSAGE)
            {
                this.lines.add("... (max message size exceeded)");
            }
        }

        private boolean maxMessageSizeReached()
        {
            return this.lines.size() >= MAX_LINES_FOR_MESSAGE;
        }

        private void printLines(String text)
        {
            ArrayIterate.forEach(this.lineSplitter.split(text), this::addLine);
        }

        private String createSummaryMessage(MutableList<Diagnostic<? extends JavaFileObject>> diagnostics, String description)
        {
            StringBuilder builder = new StringBuilder().append(diagnostics.size()).append(' ').append(description);
            if (diagnostics.size() > 1)
            {
                builder.append('s');
            }
            builder.append(" compiling ");
            MutableList<String> sourceNames = diagnostics.collect(PureJavaCompileException::getSourceName, Sets.mutable.empty()).without(null).toSortedList();
            if (sourceNames.size() <= MAX_SOURCES_FOR_MESSAGE)
            {
                sourceNames.appendString(builder, ", ");
            }
            else
            {
                sourceNames.subList(0, MAX_SOURCES_FOR_MESSAGE).appendString(builder, "", ", ", ", ... (and ");
                builder.append(sourceNames.size() - MAX_SOURCES_FOR_MESSAGE).append(" more)");
            }
            return builder.toString();
        }

        private void printDiagnosticSources(String sourceName, Iterable<? extends Diagnostic<? extends JavaFileObject>> diagnostics)
        {
            if (maxMessageSizeReached())
            {
                return;
            }

            Diagnostic<? extends JavaFileObject> firstDiagnostic = Iterate.getFirst(diagnostics);
            if (firstDiagnostic == null)
            {
                return;
            }

            JavaFileObject source = firstDiagnostic.getSource();
            String[] sourceLines;
            if (source instanceof StringJavaSource)
            {
                sourceLines = this.lineSplitter.split(((StringJavaSource) source).getCode());
                addLine("");
                addLine(sourceName);
            }
            else
            {
                sourceLines = new String[0];
            }

            long sourceLinesHighwater = 0;
            for (Diagnostic<? extends JavaFileObject> diagnostic : diagnostics)
            {
                if (maxMessageSizeReached())
                {
                    return;
                }

                long lineNo = Math.max(diagnostic.getLineNumber() - SOURCE_CONTEXT_LINES, sourceLinesHighwater + 1);
                long end = Math.min(diagnostic.getLineNumber() + SOURCE_CONTEXT_LINES, sourceLines.length);
                if (lineNo - sourceLinesHighwater > 2)
                {
                    addLine(String.format("%04d:%04d ...", sourceLinesHighwater + 1, lineNo - 1));
                    sourceLinesHighwater = lineNo - 1;
                }
                else
                {
                    lineNo = sourceLinesHighwater + 1;
                }

                while (lineNo < end)
                {
                    if (sourceLinesHighwater < lineNo)
                    {
                        addLine(String.format("%04d %s", lineNo, sourceLines[(int) (lineNo - 1)]));
                        sourceLinesHighwater = lineNo;
                    }
                    lineNo++;
                }
            }
        }
    }
}
